In [1]:
import numpy as np
import pandas as pd
import os
import cv2

# Define path to the dataset
PATH = "C:/Users/emanu/Universidade/Mestrado/1_Ano/2_Semestre/ACA/Projeto/ACA-Project/AML-Project2/dataset"

# Read the training set data
train_data = np.load(os.path.join(PATH, "trainX.npy"))
train_labels = np.load(os.path.join(PATH, "trainy.npy"), allow_pickle=True)

print(train_data.shape)
display(train_data)

# Read the test set data
test_data = np.load(os.path.join(PATH, "testX.npy"))

# Read the CSV file containing the image paths and labels
train_df = pd.read_csv(os.path.join(PATH, "train_intel-image-classification-csvdata.csv"))
test_df = pd.read_csv(os.path.join(PATH, "test_intel-image-classification-csvdata-kaggle.csv"))

display(train_df)

'''
# Display some sample images from the training set
for i in range(5):
    img = train_data[i]
    label = train_labels[i]
    label_name = train_df.loc[label]["class"]
    cv2.imshow(str(label_name), img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
'''

(12000, 50, 50, 3)


array([[[[ 47,  64,  77],
         [ 43,  57,  80],
         [182, 206, 224],
         ...,
         [ 10,   8,   8],
         [  9,   7,   7],
         [  7,   5,   5]],

        [[ 42,  59,  80],
         [ 14,  22,  35],
         [ 50,  62,  74],
         ...,
         [ 14,   9,  10],
         [ 10,   5,   6],
         [ 11,   6,   7]],

        [[ 51,  68,  87],
         [  0,   5,   9],
         [  7,  14,  23],
         ...,
         [ 13,   8,  10],
         [ 13,   8,   9],
         [ 11,   6,   7]],

        ...,

        [[ 57,  63,  76],
         [ 43,  55,  65],
         [ 33,  45,  63],
         ...,
         [ 37,  36,  40],
         [ 17,  12,  14],
         [ 16,  11,  13]],

        [[ 48,  58,  65],
         [ 47,  53,  66],
         [ 45,  53,  60],
         ...,
         [ 19,  21,  22],
         [ 25,  20,  22],
         [ 14,   9,  10]],

        [[ 32,  40,  47],
         [ 13,  19,  30],
         [ 11,  17,  24],
         ...,
         [237, 239, 247],
        

number                                           filename  class  \
0           0  intel-image-classification-aca/seg_train/seg_t...      0   
1           1  intel-image-classification-aca/seg_train/seg_t...      0   
2           2  intel-image-classification-aca/seg_train/seg_t...      0   
3           3  intel-image-classification-aca/seg_train/seg_t...      0   
4           4  intel-image-classification-aca/seg_train/seg_t...      0   
...       ...                                                ...    ...   
11995   11995  intel-image-classification-aca/seg_train/seg_t...      5   
11996   11996  intel-image-classification-aca/seg_train/seg_t...      5   
11997   11997  intel-image-classification-aca/seg_train/seg_t...      5   
11998   11998  intel-image-classification-aca/seg_train/seg_t...      5   
11999   11999  intel-image-classification-aca/seg_train/seg_t...      5   

       img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0                 47             64             77             43   
1                172            116             81            169   
2                203            193            186            201   
3                 90            118            118             89   
4                236            236            236            236   
...              ...            ...            ...            ...   
11995             48             48             48             76   
11996             15             13             12             11   
11997            139            140            144            110   
11998            183            152            137             75   
11999             61             68             71            125   

       img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  ...  img_pixel_2496_b  \
0                 57             80            182  ...                64   
1                115             80            171  ...               245   
2                191            184            200  ...                 1   
3                108            116            110  ...               104   
4                236            236            236  ...               246   
...              ...            ...            ...  ...               ...   
11995             76             76             63  ...               141   
11996             15             20             29  ...                47   
11997            103             94            185  ...               197   
11998             26             28             26  ...                71   
11999            131            138             85  ...               156   

       img_pixel_2497_r  img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  \
0                   237               239               247                 0   
1                    94               220               249                95   
2                     1                 1                 1                 0   
3                    29                38                35               102   
4                   235               235               235               248   
...                 ...               ...               ...               ...   
11995               123               123               123               138   
11996                40                45                46                38   
11997               196               194               193               179   
11998               132                86                68               138   
11999               123               113               126                97   

       img_pixel_2498_g  img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  \
0                     1                 2                16                15   
1                   216               248                90               216   
2                     0                 0                 1                 1   
3                   100                99              

'\n# Display some sample images from the training set\nfor i in range(5):\n    img = train_data[i]\n    label = train_labels[i]\n    label_name = train_df.loc[label]["class"]\n    cv2.imshow(str(label_name), img)\n    cv2.waitKey(0)\n    cv2.destroyAllWindows()\n'

In [2]:
y_trainv = train_df['class']
X_trainv = train_df.drop(columns=['class', 'filename', 'number'], axis=1)

In [3]:
X_trainv = X_trainv / 255

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_trainv, y_trainv, train_size=0.8, random_state=42, stratify=y_trainv)

In [49]:
from sklearn.decomposition import PCA

pca_test = PCA(.85)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

381


In [50]:
pca_test = PCA(.90)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

725


In [51]:
pca_test = PCA(.95)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

1322


In [52]:
def pca(data, n_components): 

    ppca = PCA(n_components)    
    principalComponents = ppca.fit_transform(data) 

    principalDf = pd.DataFrame(data = principalComponents, columns = ['Principal Component ' + str(i+1) for i in range(principalComponents.shape[1])])

    return principalDf

In [53]:
pca_train = pca(X_train, 725)

display(pca_train)

In [ ]:
pca_test = pca(X_test, 725)

### MLP sklearn

In [5]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.metrics import classification_report

mlp = MLPClassifier(activation="relu", solver="adam", max_iter=100000, shuffle=False)
mlp.fit(X_train, y_train)

predict_test = mlp.predict(X_test)

print(confusion_matrix(y_test, predict_test))

print(classification_report(y_test, predict_test))

[[109   8  40  67 103  73]
 [ 27 243   7  14  39  70]
 [  9   1 237  63  70  20]
 [ 10   1  42 244  89  14]
 [ 14   4  78  73 213  18]
 [ 29  16  29  17  53 256]]
              precision    recall  f1-score   support

           0       0.55      0.27      0.36       400
           1       0.89      0.61      0.72       400
           2       0.55      0.59      0.57       400
           3       0.51      0.61      0.56       400
           4       0.38      0.53      0.44       400
           5       0.57      0.64      0.60       400

    accuracy                           0.54      2400
   macro avg       0.57      0.54      0.54      2400
weighted avg       0.57      0.54      0.54      2400



In [6]:
kaggle_df = test_df.drop(columns=['filename', 'number'], axis=1)

In [8]:
kaggle_df = kaggle_df / 255

pca_kaggle = pca(kaggle_df, 725)

predict_kaggle = mlp.predict(kaggle_df)

In [10]:
submission = pd.DataFrame({'number': test_df['number'], 'class': predict_kaggle})
print(submission)
submission.to_csv('submission_mlp_PCA.csv', index=False)

      number  class
0          0      4
1          1      1
2          2      0
3          3      4
4          4      2
...      ...    ...
5046    5046      4
5047    5047      4
5048    5048      0
5049    5049      1
5050    5050      2

[5051 rows x 2 columns]
