In [1]:
import numpy as np
import pandas as pd
import os
import cv2

# Define path to the dataset
PATH = "C:/Users/emanu/Universidade/Mestrado/1_Ano/2_Semestre/ACA/Projeto/ACA-Project/AML-Project2/dataset"

# Read the training set data
train_data = np.load(os.path.join(PATH, "trainX.npy"))
train_labels = np.load(os.path.join(PATH, "trainy.npy"), allow_pickle=True)

print(train_data.shape)
display(train_data)

# Read the test set data
test_data = np.load(os.path.join(PATH, "testX.npy"))

# Read the CSV file containing the image paths and labels
train_df = pd.read_csv(os.path.join(PATH, "train_intel-image-classification-csvdata.csv"))
test_df = pd.read_csv(os.path.join(PATH, "test_intel-image-classification-csvdata-kaggle.csv"))

display(train_df)

'''
# Display some sample images from the training set
for i in range(5):
    img = train_data[i]
    label = train_labels[i]
    label_name = train_df.loc[label]["class"]
    cv2.imshow(str(label_name), img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
'''

(12000, 50, 50, 3)


array([[[[ 47,  64,  77],
         [ 43,  57,  80],
         [182, 206, 224],
         ...,
         [ 10,   8,   8],
         [  9,   7,   7],
         [  7,   5,   5]],

        [[ 42,  59,  80],
         [ 14,  22,  35],
         [ 50,  62,  74],
         ...,
         [ 14,   9,  10],
         [ 10,   5,   6],
         [ 11,   6,   7]],

        [[ 51,  68,  87],
         [  0,   5,   9],
         [  7,  14,  23],
         ...,
         [ 13,   8,  10],
         [ 13,   8,   9],
         [ 11,   6,   7]],

        ...,

        [[ 57,  63,  76],
         [ 43,  55,  65],
         [ 33,  45,  63],
         ...,
         [ 37,  36,  40],
         [ 17,  12,  14],
         [ 16,  11,  13]],

        [[ 48,  58,  65],
         [ 47,  53,  66],
         [ 45,  53,  60],
         ...,
         [ 19,  21,  22],
         [ 25,  20,  22],
         [ 14,   9,  10]],

        [[ 32,  40,  47],
         [ 13,  19,  30],
         [ 11,  17,  24],
         ...,
         [237, 239, 247],
        

number                                           filename  class  \
0           0  intel-image-classification-aca/seg_train/seg_t...      0   
1           1  intel-image-classification-aca/seg_train/seg_t...      0   
2           2  intel-image-classification-aca/seg_train/seg_t...      0   
3           3  intel-image-classification-aca/seg_train/seg_t...      0   
4           4  intel-image-classification-aca/seg_train/seg_t...      0   
...       ...                                                ...    ...   
11995   11995  intel-image-classification-aca/seg_train/seg_t...      5   
11996   11996  intel-image-classification-aca/seg_train/seg_t...      5   
11997   11997  intel-image-classification-aca/seg_train/seg_t...      5   
11998   11998  intel-image-classification-aca/seg_train/seg_t...      5   
11999   11999  intel-image-classification-aca/seg_train/seg_t...      5   

       img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0                 47             64             77             43   
1                172            116             81            169   
2                203            193            186            201   
3                 90            118            118             89   
4                236            236            236            236   
...              ...            ...            ...            ...   
11995             48             48             48             76   
11996             15             13             12             11   
11997            139            140            144            110   
11998            183            152            137             75   
11999             61             68             71            125   

       img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  ...  img_pixel_2496_b  \
0                 57             80            182  ...                64   
1                115             80            171  ...               245   
2                191            184            200  ...                 1   
3                108            116            110  ...               104   
4                236            236            236  ...               246   
...              ...            ...            ...  ...               ...   
11995             76             76             63  ...               141   
11996             15             20             29  ...                47   
11997            103             94            185  ...               197   
11998             26             28             26  ...                71   
11999            131            138             85  ...               156   

       img_pixel_2497_r  img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  \
0                   237               239               247                 0   
1                    94               220               249                95   
2                     1                 1                 1                 0   
3                    29                38                35               102   
4                   235               235               235               248   
...                 ...               ...               ...               ...   
11995               123               123               123               138   
11996                40                45                46                38   
11997               196               194               193               179   
11998               132                86                68               138   
11999               123               113               126                97   

       img_pixel_2498_g  img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  \
0                     1                 2                16                15   
1                   216               248                90               216   
2                     0                 0                 1                 1   
3                   100                99              

'\n# Display some sample images from the training set\nfor i in range(5):\n    img = train_data[i]\n    label = train_labels[i]\n    label_name = train_df.loc[label]["class"]\n    cv2.imshow(str(label_name), img)\n    cv2.waitKey(0)\n    cv2.destroyAllWindows()\n'

In [2]:
y_trainv = train_df['class']
X_trainv = train_df.drop(columns=['class', 'filename', 'number'], axis=1)

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_rem, y_train, y_rem = train_test_split(X_trainv, y_trainv, train_size=0.6, random_state=42, stratify=y_trainv)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size=0.5, random_state=42, stratify=y_rem)

In [4]:
from sklearn.decomposition import PCA

pca_test = PCA(.85)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

381


In [5]:
pca_test = PCA(.90)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

725


In [6]:
pca_test = PCA(.95)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

1322


In [7]:
def pca(data, target, n_components): 

    ppca = PCA(n_components)    
    principalComponents = ppca.fit_transform(data) 

    principalDf = pd.DataFrame(data = principalComponents, columns = ['Principal Component ' + str(i+1) for i in range(principalComponents.shape[1])])

    return principalDf

In [14]:
pca_train = pca(X_train, y_train, 381)

display(pca_train)

Principal Component 1  Principal Component 2  Principal Component 3  \
0                875.282148            -730.069917           -1615.294621   
1               -219.361826             196.136197            3202.547554   
2              -1200.599877            -842.639781           -1881.332208   
3               3415.765676             470.955751           -1383.571386   
4              -4251.848696           -1547.632824           -1257.254289   
...                     ...                    ...                    ...   
7195            2246.900200            2104.697448           -1944.050058   
7196           -4367.937745            -722.099808           -1108.285508   
7197             969.700366           -1213.561297           -2206.258062   
7198            1798.700683             460.630069             598.380520   
7199           -1288.290314           -1138.452369             817.928251   

      Principal Component 4  Principal Component 5  Principal Component 6  \
0               -712.624300            -583.686282            1910.244356   
1                373.314187             290.209043             180.212872   
2              -1541.360249            1166.440218             836.290825   
3                851.949886             439.200401           -2032.024341   
4               -339.672586             997.937490            1142.241525   
...                     ...                    ...                    ...   
7195            -971.352293             711.101589             241.471866   
7196            -231.527825            -334.236307            -464.921780   
7197            -965.401130             609.543173            -159.076153   
7198            1628.664668             489.850401            -416.199565   
7199             367.592384             912.772274           -1293.314931   

      Principal Component 7  Principal Component 8  Principal Component 9  \
0                 81.576062              62.341409            -989.543665   
1                422.795947             348.420569            -406.852045   
2               -434.816690            -260.412709             -14.980553   
3               1644.671734            -249.508681            -589.968606   
4              -1479.868888           -1348.529291            1313.616390   
...                     ...                    ...                    ...   
7195           -1102.646367            -570.902298            -582.620423   
7196             537.876363            -218.621697             -94.942028   
7197             734.749078           -1207.037524             276.041602   
7198            -235.262588            -624.281422            -878.961117   
7199             453.221514            -620.728474            -383.170872   

      Principal Component 10  ...  Principal Component 372  \
0                -831.441013  ...               -39.862042   
1                 215.953993  ...                -7.569266   
2                -511.645880  ...                16.632360   
3                -170.010357  ...                 8.602356   
4                1623.035638  ...                -0.757602   
...                      ...  ...                      ...   
7195             -275.838389  ...              -119.546892   
7196             -835.889516  ...               -51.374195   
7197               89.075956  ...               -83.359080   
7198             -161.821044  ...                61.962955   
7199              244.504484  ...               120.789897   

      Principal Component 373  Principal Component 374  \
0                   32.110482               -45.870951   
1                   63.403247               -19.492476   
2                  -56.402515                84.480510   
3                   60.601150                62.094886   
4                   75.061622                46.463400   
...                       ...                      ...   
7195               -78.485700               108.528284   
7196                10

In [15]:
pca_valid = pca(X_valid, y_valid, 381)

### MLP sklearn

In [16]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.metrics import classification_report

mlp = MLPClassifier()
mlp.fit(pca_train, y_train)

predict_test = mlp.predict(pca_valid)

print(confusion_matrix(y_valid, predict_test))

print(classification_report(y_valid, predict_test))

[[ 97  44  58  54  58  89]
 [ 49 229  22   9  33  58]
 [ 61  19 144  69  67  40]
 [ 53  29  77 127  68  46]
 [ 64  35  62  73 106  60]
 [119  62  51  35  52  81]]
              precision    recall  f1-score   support

           0       0.22      0.24      0.23       400
           1       0.55      0.57      0.56       400
           2       0.35      0.36      0.35       400
           3       0.35      0.32      0.33       400
           4       0.28      0.27      0.27       400
           5       0.22      0.20      0.21       400

    accuracy                           0.33      2400
   macro avg       0.33      0.33      0.33      2400
weighted avg       0.33      0.33      0.33      2400

