In [19]:
import numpy as np
import pandas as pd
import os
import cv2

# Define path to the dataset
PATH = "C:/Users/emanu/Universidade/Mestrado/1_Ano/2_Semestre/ACA/Projeto/ACA-Project/AML-Project2/dataset"

# Read the training set data
train_data = np.load(os.path.join(PATH, "trainX.npy"))
train_labels = np.load(os.path.join(PATH, "trainy.npy"), allow_pickle=True)

print(train_data.shape)
display(train_data)

# Read the test set data
test_data = np.load(os.path.join(PATH, "testX.npy"))

# Read the CSV file containing the image paths and labels
train_df = pd.read_csv(os.path.join(PATH, "train_intel-image-classification-csvdata.csv"))
test_df = pd.read_csv(os.path.join(PATH, "test_intel-image-classification-csvdata-kaggle.csv"))

display(train_df)

'''
# Display some sample images from the training set
for i in range(5):
    img = train_data[i]
    label = train_labels[i]
    label_name = train_df.loc[label]["class"]
    cv2.imshow(str(label_name), img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
'''

(12000, 50, 50, 3)


array([[[[ 47,  64,  77],
         [ 43,  57,  80],
         [182, 206, 224],
         ...,
         [ 10,   8,   8],
         [  9,   7,   7],
         [  7,   5,   5]],

        [[ 42,  59,  80],
         [ 14,  22,  35],
         [ 50,  62,  74],
         ...,
         [ 14,   9,  10],
         [ 10,   5,   6],
         [ 11,   6,   7]],

        [[ 51,  68,  87],
         [  0,   5,   9],
         [  7,  14,  23],
         ...,
         [ 13,   8,  10],
         [ 13,   8,   9],
         [ 11,   6,   7]],

        ...,

        [[ 57,  63,  76],
         [ 43,  55,  65],
         [ 33,  45,  63],
         ...,
         [ 37,  36,  40],
         [ 17,  12,  14],
         [ 16,  11,  13]],

        [[ 48,  58,  65],
         [ 47,  53,  66],
         [ 45,  53,  60],
         ...,
         [ 19,  21,  22],
         [ 25,  20,  22],
         [ 14,   9,  10]],

        [[ 32,  40,  47],
         [ 13,  19,  30],
         [ 11,  17,  24],
         ...,
         [237, 239, 247],
        

number                                           filename  class  \
0           0  intel-image-classification-aca/seg_train/seg_t...      0   
1           1  intel-image-classification-aca/seg_train/seg_t...      0   
2           2  intel-image-classification-aca/seg_train/seg_t...      0   
3           3  intel-image-classification-aca/seg_train/seg_t...      0   
4           4  intel-image-classification-aca/seg_train/seg_t...      0   
...       ...                                                ...    ...   
11995   11995  intel-image-classification-aca/seg_train/seg_t...      5   
11996   11996  intel-image-classification-aca/seg_train/seg_t...      5   
11997   11997  intel-image-classification-aca/seg_train/seg_t...      5   
11998   11998  intel-image-classification-aca/seg_train/seg_t...      5   
11999   11999  intel-image-classification-aca/seg_train/seg_t...      5   

       img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0                 47             64             77             43   
1                172            116             81            169   
2                203            193            186            201   
3                 90            118            118             89   
4                236            236            236            236   
...              ...            ...            ...            ...   
11995             48             48             48             76   
11996             15             13             12             11   
11997            139            140            144            110   
11998            183            152            137             75   
11999             61             68             71            125   

       img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  ...  img_pixel_2496_b  \
0                 57             80            182  ...                64   
1                115             80            171  ...               245   
2                191            184            200  ...                 1   
3                108            116            110  ...               104   
4                236            236            236  ...               246   
...              ...            ...            ...  ...               ...   
11995             76             76             63  ...               141   
11996             15             20             29  ...                47   
11997            103             94            185  ...               197   
11998             26             28             26  ...                71   
11999            131            138             85  ...               156   

       img_pixel_2497_r  img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  \
0                   237               239               247                 0   
1                    94               220               249                95   
2                     1                 1                 1                 0   
3                    29                38                35               102   
4                   235               235               235               248   
...                 ...               ...               ...               ...   
11995               123               123               123               138   
11996                40                45                46                38   
11997               196               194               193               179   
11998               132                86                68               138   
11999               123               113               126                97   

       img_pixel_2498_g  img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  \
0                     1                 2                16                15   
1                   216               248                90               216   
2                     0                 0                 1                 1   
3                   100                99              

'\n# Display some sample images from the training set\nfor i in range(5):\n    img = train_data[i]\n    label = train_labels[i]\n    label_name = train_df.loc[label]["class"]\n    cv2.imshow(str(label_name), img)\n    cv2.waitKey(0)\n    cv2.destroyAllWindows()\n'

In [20]:
y_trainv = train_df['class']
X_trainv = train_df.drop(columns=['class', 'filename', 'number'], axis=1)

In [21]:
#X_trainv = X_trainv / 255

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_trainv, y_trainv, train_size=0.8, random_state=42, stratify=y_trainv)

In [ ]:
from sklearn.decomposition import PCA

pca_test = PCA(.85)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

In [ ]:
pca_test = PCA(.90)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

725


In [ ]:
pca_test = PCA(.95)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

1322


In [23]:
def pca(data, n_components): 

    ppca = PCA(n_components)    
    principalComponents = ppca.fit_transform(data) 

    principalDf = pd.DataFrame(data = principalComponents, columns = ['Principal Component ' + str(i+1) for i in range(principalComponents.shape[1])])

    return principalDf

In [25]:
pca_train = pca(X_train, 725)

display(pca_train)

Principal Component 1  Principal Component 2  Principal Component 3  \
0                -87.236164           -1771.661868           -2291.812274   
1               2610.923334             970.461469             139.179581   
2               4020.218069           -1799.755497             -66.844888   
3                845.958814            -920.712145             574.017910   
4               1268.019628            -382.838009             -99.571864   
...                     ...                    ...                    ...   
9595           -2519.614888            1605.099347             745.649048   
9596            2233.525004            1702.026192            -178.074381   
9597           -5676.258627            1838.241341             636.412564   
9598            1785.824810             438.940256             582.816502   
9599           -2409.919721           -1330.412414            1185.698789   

      Principal Component 4  Principal Component 5  Principal Component 6  \
0               -574.618068             857.922959           -2548.284129   
1               -725.154285            -293.300503              77.478637   
2               -262.380987            1122.292840           -4274.693889   
3              -1224.494143            -658.595861            -265.853374   
4                780.161614            -550.102327            -646.530524   
...                     ...                    ...                    ...   
9595             267.073031            -393.778350            -124.091029   
9596              78.888898             159.689481             517.295706   
9597            1021.370725             893.035515            -391.665119   
9598            1683.185702             352.752881            -321.326133   
9599            -197.888241             988.874629              25.297750   

      Principal Component 7  Principal Component 8  Principal Component 9  \
0                129.019083            -766.536894            -372.000265   
1                 68.400064             145.332310            -259.183553   
2                561.118323             107.323736           -1066.941921   
3                 22.515116            1067.794962             264.210768   
4               -187.036356            1528.418451            -979.537378   
...                     ...                    ...                    ...   
9595           -1715.994514             850.630234             537.384225   
9596            -526.125991            -273.235363            -194.987656   
9597            -385.272569              64.775757            -782.419715   
9598            -248.219652             832.850712            -665.618047   
9599            -631.598660             -23.127389             614.791692   

      Principal Component 10  ...  Principal Component 716  \
0                 282.286154  ...               -22.688449   
1                -440.958794  ...               -94.994307   
2                 -89.567211  ...               -14.200596   
3                 703.725914  ...               -34.657050   
4                -489.066611  ...               -14.847296   
...                      ...  ...                      ...   
9595              -33.587588  ...                69.543398   
9596              926.308710  ...                35.385287   
9597              195.951827  ...                -4.837468   
9598             -202.583926  ...              -114.497516   
9599             -301.091989  ...              -101.089186   

      Principal Component 717  Principal Component 718  \
0                   40.154068               -16.485310   
1                 -123.276212               -18.344318   
2                  -50.791301                40.747433   
3                  -61.316352               -44.175578   
4                 -102.212568                26.087902   
...                       ...                      ...   
9595               -32.492993                76.537632   
9596                94

In [26]:
pca_test = pca(X_test, 725)

### MLP sklearn

In [27]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.metrics import classification_report

mlp = MLPClassifier(activation="relu", solver="adam", max_iter=100000, shuffle=False)
mlp.fit(pca_train, y_train)

predict_test = mlp.predict(pca_test)

print(confusion_matrix(y_test, predict_test))

print(classification_report(y_test, predict_test))

[[100  71  65  38  51  75]
 [ 51 200  15  12  29  93]
 [ 56  39 126  76  70  33]
 [ 43  26  57 192  59  23]
 [ 50  58  74  83  91  44]
 [ 95 116  35  25  41  88]]
              precision    recall  f1-score   support

           0       0.25      0.25      0.25       400
           1       0.39      0.50      0.44       400
           2       0.34      0.32      0.33       400
           3       0.45      0.48      0.46       400
           4       0.27      0.23      0.25       400
           5       0.25      0.22      0.23       400

    accuracy                           0.33      2400
   macro avg       0.32      0.33      0.33      2400
weighted avg       0.32      0.33      0.33      2400



In [ ]:
kaggle_df = test_df.drop(columns=['filename', 'number'], axis=1)

In [ ]:
kaggle_df = kaggle_df / 255

pca_kaggle = pca(kaggle_df, 725)

predict_kaggle = mlp.predict(pca_kaggle)

In [ ]:
submission = pd.DataFrame({'number': test_df['number'], 'class': predict_kaggle})
print(submission)
submission.to_csv('submission_mlp_PCA.csv', index=False)

      number  class
0          0      4
1          1      1
2          2      0
3          3      4
4          4      2
...      ...    ...
5046    5046      4
5047    5047      4
5048    5048      0
5049    5049      1
5050    5050      2

[5051 rows x 2 columns]
