In [17]:
import numpy as np
import pandas as pd
import os
import cv2

# Define path to the dataset
PATH = "C:/Users/emanu/Universidade/Mestrado/1_Ano/2_Semestre/ACA/Projeto/ACA-Project/AML-Project2/dataset"

# Read the training set data
train_data = np.load(os.path.join(PATH, "trainX.npy"))
train_labels = np.load(os.path.join(PATH, "trainy.npy"), allow_pickle=True)

print(train_data.shape)
display(train_data)

# Read the test set data
test_data = np.load(os.path.join(PATH, "testX.npy"))

# Read the CSV file containing the image paths and labels
train_df = pd.read_csv(os.path.join(PATH, "train_intel-image-classification-csvdata.csv"))
test_df = pd.read_csv(os.path.join(PATH, "test_intel-image-classification-csvdata-kaggle.csv"))

display(train_df)

'''
# Display some sample images from the training set
for i in range(5):
    img = train_data[i]
    label = train_labels[i]
    label_name = train_df.loc[label]["class"]
    cv2.imshow(str(label_name), img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
'''

(12000, 50, 50, 3)


array([[[[ 47,  64,  77],
         [ 43,  57,  80],
         [182, 206, 224],
         ...,
         [ 10,   8,   8],
         [  9,   7,   7],
         [  7,   5,   5]],

        [[ 42,  59,  80],
         [ 14,  22,  35],
         [ 50,  62,  74],
         ...,
         [ 14,   9,  10],
         [ 10,   5,   6],
         [ 11,   6,   7]],

        [[ 51,  68,  87],
         [  0,   5,   9],
         [  7,  14,  23],
         ...,
         [ 13,   8,  10],
         [ 13,   8,   9],
         [ 11,   6,   7]],

        ...,

        [[ 57,  63,  76],
         [ 43,  55,  65],
         [ 33,  45,  63],
         ...,
         [ 37,  36,  40],
         [ 17,  12,  14],
         [ 16,  11,  13]],

        [[ 48,  58,  65],
         [ 47,  53,  66],
         [ 45,  53,  60],
         ...,
         [ 19,  21,  22],
         [ 25,  20,  22],
         [ 14,   9,  10]],

        [[ 32,  40,  47],
         [ 13,  19,  30],
         [ 11,  17,  24],
         ...,
         [237, 239, 247],
        

number                                           filename  class  \
0           0  intel-image-classification-aca/seg_train/seg_t...      0   
1           1  intel-image-classification-aca/seg_train/seg_t...      0   
2           2  intel-image-classification-aca/seg_train/seg_t...      0   
3           3  intel-image-classification-aca/seg_train/seg_t...      0   
4           4  intel-image-classification-aca/seg_train/seg_t...      0   
...       ...                                                ...    ...   
11995   11995  intel-image-classification-aca/seg_train/seg_t...      5   
11996   11996  intel-image-classification-aca/seg_train/seg_t...      5   
11997   11997  intel-image-classification-aca/seg_train/seg_t...      5   
11998   11998  intel-image-classification-aca/seg_train/seg_t...      5   
11999   11999  intel-image-classification-aca/seg_train/seg_t...      5   

       img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0                 47             64             77             43   
1                172            116             81            169   
2                203            193            186            201   
3                 90            118            118             89   
4                236            236            236            236   
...              ...            ...            ...            ...   
11995             48             48             48             76   
11996             15             13             12             11   
11997            139            140            144            110   
11998            183            152            137             75   
11999             61             68             71            125   

       img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  ...  img_pixel_2496_b  \
0                 57             80            182  ...                64   
1                115             80            171  ...               245   
2                191            184            200  ...                 1   
3                108            116            110  ...               104   
4                236            236            236  ...               246   
...              ...            ...            ...  ...               ...   
11995             76             76             63  ...               141   
11996             15             20             29  ...                47   
11997            103             94            185  ...               197   
11998             26             28             26  ...                71   
11999            131            138             85  ...               156   

       img_pixel_2497_r  img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  \
0                   237               239               247                 0   
1                    94               220               249                95   
2                     1                 1                 1                 0   
3                    29                38                35               102   
4                   235               235               235               248   
...                 ...               ...               ...               ...   
11995               123               123               123               138   
11996                40                45                46                38   
11997               196               194               193               179   
11998               132                86                68               138   
11999               123               113               126                97   

       img_pixel_2498_g  img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  \
0                     1                 2                16                15   
1                   216               248                90               216   
2                     0                 0                 1                 1   
3                   100                99              

'\n# Display some sample images from the training set\nfor i in range(5):\n    img = train_data[i]\n    label = train_labels[i]\n    label_name = train_df.loc[label]["class"]\n    cv2.imshow(str(label_name), img)\n    cv2.waitKey(0)\n    cv2.destroyAllWindows()\n'

In [18]:
y_trainv = train_df['class']
X_trainv = train_df.drop(columns=['class', 'filename', 'number'], axis=1)

In [19]:
X_trainv = X_trainv / 255

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_rem, y_train, y_rem = train_test_split(X_trainv, y_trainv, train_size=0.6, random_state=42, stratify=y_trainv)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size=0.5, random_state=42, stratify=y_rem)

In [22]:
from sklearn.decomposition import PCA

pca_test = PCA(.85)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

381


In [23]:
pca_test = PCA(.90)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

725


In [24]:
pca_test = PCA(.95)
pca_test.fit(X_trainv)
print(pca_test.n_components_)

1322


In [32]:
def pca(data, n_components): 

    ppca = PCA(n_components)    
    principalComponents = ppca.fit_transform(data) 

    principalDf = pd.DataFrame(data = principalComponents, columns = ['Principal Component ' + str(i+1) for i in range(principalComponents.shape[1])])

    return principalDf

In [33]:
pca_train = pca(X_train, 725)

display(pca_train)

Principal Component 1  Principal Component 2  Principal Component 3  \
0                  3.432479              -2.863019              -6.334489   
1                 -0.860242               0.769162              12.559010   
2                 -4.708235              -3.304470              -7.377773   
3                 13.395160               1.846885              -5.425770   
4                -16.673916              -6.069148              -4.930409   
...                     ...                    ...                    ...   
7195               8.811373               8.253715              -7.623726   
7196             -17.129168              -2.831764              -4.346218   
7197               3.802747              -4.759064              -8.651992   
7198               7.053728               1.806392               2.346590   
7199              -5.052119              -4.464519               3.207562   

      Principal Component 4  Principal Component 5  Principal Component 6  \
0                 -2.794605              -2.288966               7.491154   
1                  1.463977               1.138075               0.706717   
2                 -6.044550               4.574275               3.279572   
3                  3.340980               1.722355              -7.968723   
4                 -1.332049               3.913480               4.479379   
...                     ...                    ...                    ...   
7195              -3.809225               2.788634               0.946948   
7196              -0.907952              -1.310731              -1.823223   
7197              -3.785887               2.390365              -0.623828   
7198               6.386920               1.920982              -1.632155   
7199               1.441539               3.579499              -5.071823   

      Principal Component 7  Principal Component 8  Principal Component 9  \
0                  0.319906               0.244476              -3.880563   
1                  1.658023               1.366355              -1.595498   
2                 -1.705163              -1.021226              -0.058747   
3                  6.449693              -0.978465              -2.313602   
4                 -5.803407              -5.288350               5.151437   
...                     ...                    ...                    ...   
7195              -4.324103              -2.238833              -2.284786   
7196               2.109319              -0.857340              -0.372322   
7197               2.881369              -4.733480               1.082516   
7198              -0.922598              -2.448162              -3.446906   
7199               1.777339              -2.434229              -1.502631   

      Principal Component 10  ...  Principal Component 716  \
0                  -3.260553  ...                 0.385775   
1                   0.846878  ...                -0.176457   
2                  -2.006454  ...                 0.032817   
3                  -0.666707  ...                -0.019859   
4                   6.364846  ...                 0.365924   
...                      ...  ...                      ...   
7195               -1.081719  ...                 0.388924   
7196               -3.277998  ...                 0.005933   
7197                0.349317  ...                 0.113620   
7198               -0.634592  ...                 0.612504   
7199                0.958841  ...                 0.002991   

      Principal Component 717  Principal Component 718  \
0                   -0.190927                -0.114338   
1                   -0.086531                -0.102756   
2                    0.086299                 0.072503   
3                   -0.328082                 0.388305   
4                    0.284998                 0.269533   
...                       ...                      ...   
7195                -0.132988                 0.059485   
7196                -0

In [34]:
pca_valid = pca(X_valid, 725)

### MLP sklearn

In [38]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.metrics import classification_report

mlp = MLPClassifier(activation="relu", solver="adam", max_iter=100000, shuffle=False)
mlp.fit(pca_train, y_train)

predict_test = mlp.predict(pca_valid)

print(confusion_matrix(y_valid, predict_test))

print(classification_report(y_valid, predict_test))

[[104  36  79  47  56  78]
 [ 36 244  18  14  37  51]
 [ 50  20 154  58  75  43]
 [ 41  18  56 185  47  53]
 [ 43  32  77  73 107  68]
 [115  58  57  34  49  87]]
              precision    recall  f1-score   support

           0       0.27      0.26      0.26       400
           1       0.60      0.61      0.60       400
           2       0.35      0.39      0.37       400
           3       0.45      0.46      0.46       400
           4       0.29      0.27      0.28       400
           5       0.23      0.22      0.22       400

    accuracy                           0.37      2400
   macro avg       0.36      0.37      0.37      2400
weighted avg       0.36      0.37      0.37      2400

