In [2]:
import numpy as np
import pandas as pd
import os
import cv2

# Define path to the dataset
PATH = "C:/Users/emanu/Universidade/Mestrado/1_Ano/2_Semestre/ACA/Projeto/ACA-Project/AML-Project2/dataset"

# Read the training set data
train_data = np.load(os.path.join(PATH, "trainX.npy"))
train_labels = np.load(os.path.join(PATH, "trainy.npy"), allow_pickle=True)

display(train_labels)

print(train_data.shape)
display(train_data)

# Read the test set data
test_data = np.load(os.path.join(PATH, "testX.npy"))

# Read the CSV file containing the image paths and labels
train_df = pd.read_csv(os.path.join(PATH, "train_intel-image-classification-csvdata.csv"))
test_df = pd.read_csv(os.path.join(PATH, "test_intel-image-classification-csvdata-kaggle.csv"))

display(train_df)

'''
# Display some sample images from the training set
for i in range(5):
    img = train_data[i]
    label = train_labels[i]
    label_name = train_df.loc[label]["class"]
    cv2.imshow(str(label_name), img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
'''

array([0, 0, 0, ..., 5, 5, 5], dtype=object)

(12000, 50, 50, 3)


array([[[[ 47,  64,  77],
         [ 43,  57,  80],
         [182, 206, 224],
         ...,
         [ 10,   8,   8],
         [  9,   7,   7],
         [  7,   5,   5]],

        [[ 42,  59,  80],
         [ 14,  22,  35],
         [ 50,  62,  74],
         ...,
         [ 14,   9,  10],
         [ 10,   5,   6],
         [ 11,   6,   7]],

        [[ 51,  68,  87],
         [  0,   5,   9],
         [  7,  14,  23],
         ...,
         [ 13,   8,  10],
         [ 13,   8,   9],
         [ 11,   6,   7]],

        ...,

        [[ 57,  63,  76],
         [ 43,  55,  65],
         [ 33,  45,  63],
         ...,
         [ 37,  36,  40],
         [ 17,  12,  14],
         [ 16,  11,  13]],

        [[ 48,  58,  65],
         [ 47,  53,  66],
         [ 45,  53,  60],
         ...,
         [ 19,  21,  22],
         [ 25,  20,  22],
         [ 14,   9,  10]],

        [[ 32,  40,  47],
         [ 13,  19,  30],
         [ 11,  17,  24],
         ...,
         [237, 239, 247],
        

number                                           filename  class  \
0           0  intel-image-classification-aca/seg_train/seg_t...      0   
1           1  intel-image-classification-aca/seg_train/seg_t...      0   
2           2  intel-image-classification-aca/seg_train/seg_t...      0   
3           3  intel-image-classification-aca/seg_train/seg_t...      0   
4           4  intel-image-classification-aca/seg_train/seg_t...      0   
...       ...                                                ...    ...   
11995   11995  intel-image-classification-aca/seg_train/seg_t...      5   
11996   11996  intel-image-classification-aca/seg_train/seg_t...      5   
11997   11997  intel-image-classification-aca/seg_train/seg_t...      5   
11998   11998  intel-image-classification-aca/seg_train/seg_t...      5   
11999   11999  intel-image-classification-aca/seg_train/seg_t...      5   

       img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0                 47             64             77             43   
1                172            116             81            169   
2                203            193            186            201   
3                 90            118            118             89   
4                236            236            236            236   
...              ...            ...            ...            ...   
11995             48             48             48             76   
11996             15             13             12             11   
11997            139            140            144            110   
11998            183            152            137             75   
11999             61             68             71            125   

       img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  ...  img_pixel_2496_b  \
0                 57             80            182  ...                64   
1                115             80            171  ...               245   
2                191            184            200  ...                 1   
3                108            116            110  ...               104   
4                236            236            236  ...               246   
...              ...            ...            ...  ...               ...   
11995             76             76             63  ...               141   
11996             15             20             29  ...                47   
11997            103             94            185  ...               197   
11998             26             28             26  ...                71   
11999            131            138             85  ...               156   

       img_pixel_2497_r  img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  \
0                   237               239               247                 0   
1                    94               220               249                95   
2                     1                 1                 1                 0   
3                    29                38                35               102   
4                   235               235               235               248   
...                 ...               ...               ...               ...   
11995               123               123               123               138   
11996                40                45                46                38   
11997               196               194               193               179   
11998               132                86                68               138   
11999               123               113               126                97   

       img_pixel_2498_g  img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  \
0                     1                 2                16                15   
1                   216               248                90               216   
2                     0                 0                 1                 1   
3                   100                99              

'\n# Display some sample images from the training set\nfor i in range(5):\n    img = train_data[i]\n    label = train_labels[i]\n    label_name = train_df.loc[label]["class"]\n    cv2.imshow(str(label_name), img)\n    cv2.waitKey(0)\n    cv2.destroyAllWindows()\n'

In [3]:
y_trainv = train_df['class']
X_trainv = train_df.drop(columns=['class', 'filename', 'number'], axis=1)

In [4]:
X_trainv = X_trainv / 255

'''
cols = X_trainv.columns

for c in cols:
    X_trainv[c] = (X_trainv[c] - X_trainv[c].mean()) / X_trainv[c].std()
'''

display(X_trainv)

img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0           0.184314       0.250980       0.301961       0.168627   
1           0.674510       0.454902       0.317647       0.662745   
2           0.796078       0.756863       0.729412       0.788235   
3           0.352941       0.462745       0.462745       0.349020   
4           0.925490       0.925490       0.925490       0.925490   
...              ...            ...            ...            ...   
11995       0.188235       0.188235       0.188235       0.298039   
11996       0.058824       0.050980       0.047059       0.043137   
11997       0.545098       0.549020       0.564706       0.431373   
11998       0.717647       0.596078       0.537255       0.294118   
11999       0.239216       0.266667       0.278431       0.490196   

       img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  img_pixel_2_g  \
0           0.223529       0.313725       0.713725       0.807843   
1           0.450980       0.313725       0.670588       0.458824   
2           0.749020       0.721569       0.784314       0.745098   
3           0.423529       0.454902       0.431373       0.521569   
4           0.925490       0.925490       0.925490       0.925490   
...              ...            ...            ...            ...   
11995       0.298039       0.298039       0.247059       0.247059   
11996       0.058824       0.078431       0.113725       0.070588   
11997       0.403922       0.368627       0.725490       0.639216   
11998       0.101961       0.109804       0.101961       0.039216   
11999       0.513725       0.541176       0.333333       0.356863   

       img_pixel_2_b  img_pixel_3_r  ...  img_pixel_2496_b  img_pixel_2497_r  \
0           0.878431       0.027451  ...          0.250980          0.929412   
1           0.321569       0.654902  ...          0.960784          0.368627   
2           0.717647       0.803922  ...          0.003922          0.003922   
3           0.580392       0.843137  ...          0.407843          0.113725   
4           0.925490       0.925490  ...          0.964706          0.921569   
...              ...            ...  ...               ...               ...   
11995       0.247059       0.352941  ...          0.552941          0.482353   
11996       0.078431       0.019608  ...          0.184314          0.156863   
11997       0.568627       0.698039  ...          0.772549          0.768627   
11998       0.000000       0.968627  ...          0.278431          0.517647   
11999       0.384314       0.635294  ...          0.611765          0.482353   

       img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  img_pixel_2498_g  \
0              0.937255          0.968627          0.000000          0.003922   
1              0.862745          0.976471          0.372549          0.847059   
2              0.003922          0.003922          0.000000          0.000000   
3              0.149020          0.137255          0.400000          0.392157   
4              0.921569          0.921569          0.972549          0.972549   
...                 ...               ...               ...               ...   
11995          0.482353          0.482353          0.541176          0.541176   
11996          0.176471          0.180392          0.149020          0.168627   
11997          0.760784          0.756863          0.701961          0.690196   
11998          0.337255          0.266667          0.541176          0.368627   
11999          0.443137          0.494118          0.380392          0.349020   

       img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  img_pixel_2499_b  
0              0.007843          0.062745          0.058824          0.066667  
1              0.972549          0.352941          0.847059          0.984314  
2              0.000000          0.003922          0.003922          0.003922  
3              0.388235          0.333333          0.317647          0.360784  
4              

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_trainv, y_trainv, train_size=0.8, random_state=42, stratify=y_trainv)

### MLP sklearn

In [6]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
from sklearn.metrics import classification_report

mlp = MLPClassifier(activation="logistic", solver="sgd", max_iter=100000, random_state=42)
mlp.fit(X_train, y_train)

predict_test = mlp.predict(X_test)

print(confusion_matrix(y_test, predict_test))

print(classification_report(y_test, predict_test))

c:\Users\emanu\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:699: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


[[161  22  38  51  64  64]
 [ 21 306   0   9  20  44]
 [ 12   2 264  51  54  17]
 [ 24   8  41 242  76   9]
 [ 39  25  75  59 187  15]
 [ 38  33  19   9  30 271]]
              precision    recall  f1-score   support

           0       0.55      0.40      0.46       400
           1       0.77      0.77      0.77       400
           2       0.60      0.66      0.63       400
           3       0.57      0.60      0.59       400
           4       0.43      0.47      0.45       400
           5       0.65      0.68      0.66       400

    accuracy                           0.60      2400
   macro avg       0.60      0.60      0.59      2400
weighted avg       0.60      0.60      0.59      2400



In [90]:
kaggle_df = test_df.drop(columns=['filename', 'number'], axis=1)

kaggle_df = kaggle_df / 255

'''
cols = kaggle_df.columns

for c in cols:
    kaggle_df[c] = (kaggle_df[c] - kaggle_df[c].mean()) / kaggle_df[c].std()
'''

display(kaggle_df)


img_pixel_0_r  img_pixel_0_g  img_pixel_0_b  img_pixel_1_r  \
0          0.406066       0.621356       0.521823       0.009275   
1         -1.183137      -1.545189      -1.452335      -1.210134   
2         -1.195553      -1.324395      -1.372839      -1.147919   
3          0.257079      -0.841407      -1.266844       0.245691   
4          0.592301       0.110769       0.084593       0.569208   
...             ...            ...            ...            ...   
5046      -1.803920      -1.862581      -1.571580      -1.857167   
5047      -1.046565      -1.020803      -0.763367      -1.172805   
5048       0.592301       0.635155       0.588069       0.519436   
5049      -1.332125      -1.144999      -0.895861      -1.334563   
5050      -0.525108      -0.924205      -1.107851      -0.874174   

      img_pixel_1_g  img_pixel_1_b  img_pixel_2_r  img_pixel_2_g  \
0         -0.091543      -0.365119      -0.291904      -0.620487   
1         -1.578399      -1.481586      -1.186855      -1.544803   
2         -1.397753      -1.322090      -1.261434      -1.448232   
3         -0.855815      -1.282217       0.217721      -0.882606   
4          0.089103       0.060201       0.491178       0.000322   
...             ...            ...            ...            ...   
5046      -1.925795      -1.627790      -1.870498      -1.931084   
5047      -1.161523      -0.896770      -1.447882      -1.462028   
5048       0.561562       0.512105       0.491178       0.524561   
5049      -1.161523      -1.003100      -1.485172      -1.337866   
5050      -1.244898      -1.335382      -0.639940      -1.061951   

      img_pixel_2_b  img_pixel_3_r  ...  img_pixel_2496_b  img_pixel_2497_r  \
0         -0.838908       1.296021  ...         -0.949823         -0.293818   
1         -1.445594      -1.238039  ...         -0.703635         -0.887483   
2         -1.471972      -0.899328  ...          1.281254          1.608957   
3         -1.300517       0.217164  ...          0.127249          0.710847   
4         -0.087144       0.054081  ...          1.050453          2.674511   
...             ...            ...  ...               ...               ...   
5046      -1.630238      -1.902916  ...          0.158023          2.674511   
5047      -1.181817      -1.263128  ...          1.219707          0.847847   
5048       0.479976       0.781683  ...          0.773492          1.319735   
5049      -1.142251      -1.388577  ...         -1.211397         -1.207150   
5050      -1.274139      -0.460258  ...          0.250343          0.741292   

      img_pixel_2497_g  img_pixel_2497_b  img_pixel_2498_r  img_pixel_2498_g  \
0            -0.095377         -0.114123          0.393599          0.647169   
1            -0.965613         -0.854902         -0.940604         -0.951377   
2             1.597629          1.274838          0.869005          0.807024   
3             0.537523          0.456894          1.298404          1.334544   
4             2.610269          2.509470          1.405754          0.886951   
...                ...               ...               ...               ...   
5046          2.641914          2.586634          1.881160          1.846079   
5047          0.743215          0.734687          0.991691          0.886951   
5048          0.933085          0.796418          1.390418          0.998850   
5049         -1.392820         -1.333322         -1.170639         -1.367000   
5050          0.505878          1.135942          0.884341          0.854980   

      img_pixel_2498_b  img_pixel_2499_r  img_pixel_2499_g  img_pixel_2499_b  
0             0.613903          0.590365          0.841382          0.763634  
1            -0.943815         -0.848526         -0.908013         -0.830848  
2             0.567171         -0.205617         -0.303676         -0.521240  
3             1.314876          1.294503          1.238972          1.228046  
4             0.816406          1.600650          1.191261         

In [91]:
predict_kaggle = mlp.predict(kaggle_df)

In [92]:
submission = pd.DataFrame({'number': test_df['number'], 'class': predict_kaggle})
print(submission)
submission.to_csv('submission_mlp_withoutPCA_std_ls.csv', index=False)

      number  class
0          0      5
1          1      1
2          2      0
3          3      2
4          4      2
...      ...    ...
5046    5046      5
5047    5047      5
5048    5048      0
5049    5049      5
5050    5050      2

[5051 rows x 2 columns]
